name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Breaking'
    labels:
      - 'breaking'
      - 'breaking-change'
  - title: '✨ Added'
    labels:
      - 'enhancement'
      - 'feature'
      - 'added'
  - title: '🔄 Changed'
    labels:
      - 'changed'
      - 'updated'
  - title: '🐛 Fixed'
    labels:
      - 'bug'
      - 'fix'
      - 'fixed'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'documentation'
  default: patch
